2024-08-27T00:00:40 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1724716840.509361, "uuid": "3d3b918654c24dfbb5954a7be1ef0e3c"}
2024-08-27T00:00:42 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "BigQuery initialized", "timestamp": 1724716842.0052, "uuid": "8e18ae74b8cb42a4bb78498ff0389262"}
2024-08-27T00:00:42 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Connecting to BigQuery warehouse...", "timestamp": 1724716842.034305, "uuid": "56e3484952e346299c174d4e49217818"}
2024-08-27T00:00:42 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1724716842.034578, "uuid": "7a376cf62c47401bb83bf8447d163c94"}
2024-08-27T00:00:42 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716842.707564, "uuid": "5c6d8a5df50044648b2abf5738fbd066"}
2024-08-27T00:00:42 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716842.707788, "uuid": "86b262c38b5f4c8b94c851e8b6145def"}
2024-08-27T00:00:42 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "Exporting data from upstream block transform_staged_data to gold-bruin-429014-v5.trips_data_all.gcs_to_bq_transform_staged_data_v1.", "timestamp": 1724716842.707859, "uuid": "eb0b5859178d4f07aa58d1cae717a0be"}
2024-08-27T00:01:15 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716875.707277, "uuid": "b2bee0db948642f0ae2553d77d16de10"}
2024-08-27T00:01:15 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1724716875.707495, "uuid": "019ee7e5d6974af09c9d344bc106795a"}
2024-08-27T00:01:15 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Exporting data to table 'trips_data_all.taxi_yellow'...", "timestamp": 1724716875.707587, "uuid": "14150800abd64d08856f77c1aba423dc"}
2024-08-27T00:01:19 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1724716879.823744, "uuid": "0fe0d3d1e69945f2bbf1114604d04779"}
2024-08-27T00:01:19 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716879.824211, "uuid": "b7ec58a26c73407381795c60f237f008"}
2024-08-27T00:01:19 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1724716879.824489, "uuid": "c8e72a36497749449ea83d179aa135ec"}
2024-08-27T00:01:19 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1724716879.824709, "uuid": "3e9862d2ac464fa4a377ed1705f74d99"}
2024-08-27T00:01:21 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716881.183092, "uuid": "56f372a4e5574938853df2edf08b3e61"}
2024-08-27T00:01:21 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1724716881.183692, "uuid": "b48c26e55b3a452090104ca5eca73e4c"}
2024-08-27T00:01:21 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1724716881.183981, "uuid": "43fc2264cf4640d1b3e55eb961523bb0"}
2024-08-27T00:01:23 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716883.62191, "uuid": "a72e920982de4e859197eb826e550588"}
2024-08-27T00:01:23 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1724716883.622555, "uuid": "2e1a59247a8049fe9b04660dea7ef53c"}
2024-08-27T00:01:23 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1724716883.622959, "uuid": "b3ef100d149f430fb707becef6ca55e2"}
2024-08-27T00:01:27 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716887.05465, "uuid": "c183c23263764185bb11ea39fa8d62c3"}
2024-08-27T00:01:27 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1724716887.055272, "uuid": "19f0079e78f944b4a6278046f4aa6839"}
2024-08-27T00:01:27 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1724716887.055587, "uuid": "1d6618defbc449f1b8aa73065f8e4e6a"}
2024-08-27T00:01:31 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1724716891.462579, "uuid": "fcda75a5fed948779117b44073bf98fa"}
2024-08-27T00:01:31 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1724716891.463202, "uuid": "b99bd46c303c434782322b18a74f61f3"}
2024-08-27T00:01:31 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1724716891.463498, "uuid": "4333f116c2f54601b7e5c963d91ab851"}
2024-08-27T00:01:32 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0x7ce7377afac0>, attempt 1 of 1", "timestamp": 1724716892.012373, "uuid": "054d6b57398f47b7b2f5e58dd96be633", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1673, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1650, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1552, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1892, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 746, in _execute_block\n    return execute_sql_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 212, in execute_sql_code\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 204, in execute_sql_code\n    result = loader.load(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 194, in load\n    ).to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 8ca43391-8792-487a-9da1-bb77f72b04ea\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 8ca43391-8792-487a-9da1-bb77f72b04ea\n"]}
2024-08-27T00:01:32 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "EXCEPTION", "message": "Failed to execute block write_taxi_to_bq", "timestamp": 1724716892.021421, "uuid": "7e952540c3d943eda480c79c1be1cba2", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1673, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1650, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1552, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1892, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 746, in _execute_block\n    return execute_sql_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 212, in execute_sql_code\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 204, in execute_sql_code\n    result = loader.load(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 194, in load\n    ).to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 8ca43391-8792-487a-9da1-bb77f72b04ea\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 649, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 8ca43391-8792-487a-9da1-bb77f72b04ea\n"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1673, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1650, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1552, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1892, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 746, in _execute_block
    return execute_sql_code(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 212, in execute_sql_code
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 204, in execute_sql_code
    result = loader.load(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 194, in load
    ).to_dataframe()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1890, in to_dataframe
    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py", line 104, in wait_for_query
    return query_job.result(max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US

Location: US
Job ID: 8ca43391-8792-487a-9da1-bb77f72b04ea

