2024-08-07T00:18:55 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "Start executing block with BlockExecutor.", "timestamp": 1722989935.975832, "uuid": "858a79340ae843849376a3a77f581efc"}
2024-08-07T00:18:57 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "BigQuery initialized", "timestamp": 1722989937.96578, "uuid": "53be84c53aa644a8a88d4dc58bf80663"}
2024-08-07T00:18:58 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Connecting to BigQuery warehouse...", "timestamp": 1722989938.020827, "uuid": "8f0611d90045469496da513908c46b5e"}
2024-08-07T00:18:58 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1722989938.021167, "uuid": "6247f7eb718d47a486d5dbab70f5a6ea"}
2024-08-07T00:18:59 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989939.740378, "uuid": "9a16221ec8fa43eea6bdd9ea58923aa2"}
2024-08-07T00:18:59 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989939.740599, "uuid": "747b5a14e1b94bee8e983b4686b16bc1"}
2024-08-07T00:18:59 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "Exporting data from upstream block transform_staged_data to gold-bruin-429014-v5.trips_data_all.gcs_to_bq_transform_staged_data_v1.", "timestamp": 1722989939.740671, "uuid": "7426edea58d9449086bc311a129d9d47"}
2024-08-07T00:19:43 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989983.783129, "uuid": "f80fd867c33349d2bcdc9d406bce88cc"}
2024-08-07T00:19:43 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1722989983.783484, "uuid": "112d68ffe9ec46e7913b158ec4eae88d"}
2024-08-07T00:19:43 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Exporting data to table 'trips_data_all.taxi_yellow'...", "timestamp": 1722989983.783677, "uuid": "ee79c45e59a948c6966ef62b6968aa74"}
2024-08-07T00:19:48 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "DONE", "timestamp": 1722989988.305383, "uuid": "81c472a841c64d4d9dced371ff4ba8b2"}
2024-08-07T00:19:48 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989988.306086, "uuid": "f37f8ee716ba47d1a19d943230e3d662"}
2024-08-07T00:19:48 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1722989988.306448, "uuid": "7ad042d9728b4c228a561181323b5b0b"}
2024-08-07T00:19:48 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1722989988.306664, "uuid": "5f0869ace19246d88128527f0f02ff3f"}
2024-08-07T00:19:49 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989989.818238, "uuid": "59dadbfa6c13420e8a66669a17b396e6"}
2024-08-07T00:19:49 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1722989989.818698, "uuid": "5b247aa9ac8d4473a0e0196a3ce1c13d"}
2024-08-07T00:19:49 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1722989989.818952, "uuid": "2945fef889da46a6ae6434cc71f7588d"}
2024-08-07T00:19:52 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989992.315396, "uuid": "c09341f10b2d490d8babcdc59fba207c"}
2024-08-07T00:19:52 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1722989992.315756, "uuid": "dbc4f9d5d39e4142a0bface4eb99595a"}
2024-08-07T00:19:52 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1722989992.315927, "uuid": "7d0bea27c47348cb9724cf7f966bd610"}
2024-08-07T00:19:55 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722989995.7712, "uuid": "b7caa1c4e46b4da185a88835630b3450"}
2024-08-07T00:19:55 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1722989995.771799, "uuid": "4be1c3f384324f7a9f6a01ed1be56562"}
2024-08-07T00:19:55 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1722989995.77212, "uuid": "d8265efd59924e3986339a6e1408d00a"}
2024-08-07T00:20:00 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "", "timestamp": 1722990000.242159, "uuid": "8e13e6058e134789b6c407348d92ad44"}
2024-08-07T00:20:00 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u251c\u2500", "timestamp": 1722990000.242751, "uuid": "5ae13e2567b3498b9f57338ac330496e"}
2024-08-07T00:20:00 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "INFO", "message": "\u2514\u2500 Loading data...", "timestamp": 1722990000.243072, "uuid": "314b5a5b1c124ff08bb640f87ad58652"}
2024-08-07T00:20:00 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "WARNING", "message": "Exception thrown when attempting to run <function BlockExecutor.execute.<locals>.__execute_with_retry at 0x7b8aa902fb50>, attempt 1 of 1", "timestamp": 1722990000.781421, "uuid": "549edf7c9f2a4b948af671bb9589484f", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1673, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1650, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1552, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1892, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 746, in _execute_block\n    return execute_sql_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 212, in execute_sql_code\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 204, in execute_sql_code\n    result = loader.load(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 194, in load\n    ).to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 3069e443-de0e-407c-a159-e7685e0156ea\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 46, in retry_func\n    logger.warning(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 39, in warning\n    self.__send_message('warning', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 3069e443-de0e-407c-a159-e7685e0156ea\n"]}
2024-08-07T00:20:00 {"block_run_id": 27, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "block_type": "data_exporter", "level": "EXCEPTION", "message": "Failed to execute block write_taxi_to_bq", "timestamp": 1722990000.806674, "uuid": "b66957f78f1f4395853e544a233ae55f", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1673, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1650, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1552, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1892, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 746, in _execute_block\n    return execute_sql_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 212, in execute_sql_code\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 204, in execute_sql_code\n    result = loader.load(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 194, in load\n    ).to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 3069e443-de0e-407c-a159-e7685e0156ea\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 649, in execute\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 3069e443-de0e-407c-a159-e7685e0156ea\n"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1673, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1650, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1552, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1892, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 746, in _execute_block
    return execute_sql_code(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 212, in execute_sql_code
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 204, in execute_sql_code
    result = loader.load(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 194, in load
    ).to_dataframe()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1890, in to_dataframe
    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py", line 104, in wait_for_query
    return query_job.result(max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US

Location: US
Job ID: 3069e443-de0e-407c-a159-e7685e0156ea

